"""empty message

Revision ID: 3ae7302dc2f7
Revises: bc68d74da9e4
Create Date: 2021-11-23 18:23:10.761736

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '3ae7302dc2f7'
down_revision = 'bc68d74da9e4'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint('autor_nome_key', 'autor', type_='unique')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_unique_constraint('autor_nome_key', 'autor', ['nome'])
    # ### end Alembic commands ###
