"""empty message

Revision ID: 98ebed2b51a5
Revises: dfa49b585496
Create Date: 2021-11-23 21:54:31.748180

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '98ebed2b51a5'
down_revision = 'dfa49b585496'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('obra',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('titulo', sa.String(length=255), nullable=False),
    sa.Column('editora', sa.String(length=255), nullable=True),
    sa.Column('foto', sa.Text(), nullable=True),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('titulo')
    )
    op.create_table('autor',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('nome', sa.String(length=255), nullable=False),
    sa.Column('obra_id', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['obra_id'], ['obra.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.drop_table('obras')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('obras',
    sa.Column('id', sa.INTEGER(), autoincrement=True, nullable=False),
    sa.Column('titulo', sa.VARCHAR(length=255), autoincrement=False, nullable=False),
    sa.Column('editora', sa.VARCHAR(length=255), autoincrement=False, nullable=True),
    sa.Column('foto', sa.TEXT(), autoincrement=False, nullable=True),
    sa.Column('autores', sa.TEXT(), autoincrement=False, nullable=True),
    sa.PrimaryKeyConstraint('id', name='obras_pkey')
    )
    op.drop_table('autor')
    op.drop_table('obra')
    # ### end Alembic commands ###
