"""empty message

Revision ID: a74e961fb61c
Revises: dfa49b585496
Create Date: 2021-11-22 18:53:18.938241

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'a74e961fb61c'
down_revision = 'dfa49b585496'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('autores',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('nome', sa.String(length=255), nullable=False),
    sa.Column('obras_id', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['obras_id'], ['obras.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.drop_column('obras', 'autores')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('obras', sa.Column('autores', sa.TEXT(), autoincrement=False, nullable=True))
    op.drop_table('autores')
    # ### end Alembic commands ###
