"""empty message

Revision ID: dfa49b585496
Revises: 
Create Date: 2021-11-21 19:52:41.356909

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'dfa49b585496'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        'obras',
        sa.Column('id', sa.Integer(), nullable=False),
        sa.Column('titulo', sa.String(length=255), nullable=False),
        sa.Column('editora', sa.String(length=255), nullable=True),
        sa.Column('foto', sa.Text(), nullable=True),
        sa.Column('autores', sa.Text(), nullable=True),
        sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('obras')
    # ### end Alembic commands ###
